Fix errors in class definitions and add error handling to create_report methods
dcferreira/pylemmy pull request #15
Opened 2023-07-12 23:55 UTC by noenfugler

1) Some minor fixes to type definitions in CommentReportView and PostReport classes.
2) Added additional error handling to create_report in enable more graceful error handling in calling code.

2023-07-13 16:15 UTC, dcferreira requested changes
Thanks again for the contribution @noenfugler . I have some suggestions to consider, could you have a look in the comments below?

2023-07-13 16:15 UTC, dcferreira commented on pylemmy/models/comment.py
> +            raise result['error']
I don't think this is where the exception should be raised, but rather in `lemmy.post_request`.

Here's a suggestion (to change in `pylemmy/lemmy.py`:
```python
    def post_request(
        self,
        path: LemmyAPI,
        params: Optional[BaseApiModel] = None,
    ):
        """Send a POST request to the desired path.

        :param path: A Lemmy endpoint.
        :param params: Parameters to send with the request (in the body).
        """
        response = self.session.post(
            self._get_url(path),
            json=params.dict() if params is not None else {},
            timeout=self.request_timeout,
        )
        response.raise_for_status()
        return response.json()
```

Actually the same should also be done for `get_request`. Could you please implement that @noenfugler ?

2023-07-13 16:15 UTC, dcferreira commented on pylemmy/models/post.py
> +            raise result['error']
Same as the other comment, don't think the check for error should be here.

2023-07-13 21:35 UTC, noenfugler commented on pylemmy/models/comment.py
> +            raise result['error']
Happy to.  Hopefully I don't mess up the Github workflow.  I'm on a bit of a learning curve here.

2023-07-14 01:40 UTC, noenfugler commented
Changes made.  Ready for re-review.

2023-07-14 06:06 UTC, dcferreira approved these changes
Perfect, thanks a lot! :)

2023-07-14 06:07 UTC, merged